# Generated by Django 4.0 on 2023-08-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('lat_long', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
